error: properly wrap errors into error types
Let the caller has the ability to identify basic cause of error
without the need of hard-coded string contains/prefix/suffix.